# Generated by Django 4.2.7 on 2023-11-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_code', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد سینما')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('city', models.CharField(default='تهران', max_length=50, verbose_name='شهر')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سینما',
                'verbose_name_plural': 'سینما',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('director', models.CharField(blank=True, max_length=50, null=True, verbose_name='کارگردان')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سال تولید')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع نمایش')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('salable_seats', models.IntegerField(verbose_name='صندلی های قابل فروش')),
                ('free_seats', models.IntegerField(verbose_name='صندی های خالی')),
                ('status', models.CharField(choices=[('SALE_NOT_STARTED', 'فروش آغاز نشده'), ('SALE_OPEN', 'در حال فروش بلیت'), ('TICKETS_SOLD', 'بلیت ها تمام شد'), ('SALE_CLOSED', 'فروش بلیت بسته شد'), ('MOVIE_PLAYED', 'فیلم پخش شد'), ('SHOW_CANCELED', 'سکانس لغو شد')], default='SALE_NOT_STARTED', max_length=20, verbose_name='وضیعت')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.cinema', verbose_name='سینما')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'سکانس',
                'verbose_name_plural': 'سکانس',
            },
        ),
    ]
