# Generated by Django 4.2.7 on 2023-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(null=True, upload_to='cinema_image/', verbose_name='تصویر سینما'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_poster/', verbose_name='پوستر'),
        ),
    ]
