# Generated by Django 4.2.7 on 2023-11-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_cinema_poster_showtime_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='poster',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie_poster/', verbose_name='پوستر'),
        ),
    ]
